<a href="https://colab.research.google.com/github/Akshaysurtel/Commander/blob/main/Manova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from statsmodels.multivariate.manova import MANOVA

In [ ]:


X = np.random.randint(0, 100, size=(10, 5))
print('Input :\n', X)

Input :
 [[79 19 85 97 52]
 [97 84 28  1 57]
 [60 89 25 72 16]
 [57 83 60 51 41]
 [48 86  2 54 37]
 [82 52 79 61 69]
 [37 85 47 12 33]
 [76 73 24  1 35]
 [47 88 95 35 89]
 [93 40 57 70 78]]


In [ ]:
Y = np.random.randint(50, 300, size=(10, 3))
print('Target :\n', Y)

Target :
 [[239 241 166]
 [104 108 122]
 [ 54 134  67]
 [246 152 112]
 [ 75 289 205]
 [ 66 154 264]
 [154 185 153]
 [167 108 297]
 [112 200 117]
 [148  99 272]]


In [ ]:


# Y = XB^T+E
manova = MANOVA(endog=X,
                exog=Y)
result = manova.mv_test()
print(result.summary())

                 Multivariate linear model
                                                           
-----------------------------------------------------------
           x0           Value  Num DF Den DF F Value Pr > F
-----------------------------------------------------------
          Wilks' lambda 0.5476 5.0000 3.0000  0.4957 0.7699
         Pillai's trace 0.4524 5.0000 3.0000  0.4957 0.7699
 Hotelling-Lawley trace 0.8261 5.0000 3.0000  0.4957 0.7699
    Roy's greatest root 0.8261 5.0000 3.0000  0.4957 0.7699
-----------------------------------------------------------
                                                           
-----------------------------------------------------------
           x1           Value  Num DF Den DF F Value Pr > F
-----------------------------------------------------------
          Wilks' lambda 0.3284 5.0000 3.0000  1.2270 0.4617
         Pillai's trace 0.6716 5.0000 3.0000  1.2270 0.4617
 Hotelling-Lawley trace 2.0450 5.0000 3.0000  1.2270 0.46

In [ ]:
# Import necessary libraries
import pandas as pd
from statsmodels.multivariate.manova import MANOVA
from sklearn.datasets import load_iris

In [ ]:


# Load the iris dataset
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['species'] = data.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  


In [ ]:
# Rename columns to remove spaces
df.columns = ['sepal_length', 'sepal_width',
              'petal_length', 'petal_width', 'species']

In [ ]:
df.columns = ['sepal_length', 'sepal_width',
              'petal_length', 'petal_width', 'species']

In [ ]:
df['species'] = df['species'].map(
    {0: 'setosa', 1: 'versicolor', 2: 'virginica'})

In [ ]:


# Apply MANOVA with the renamed columns
manova = MANOVA.from_formula('sepal_length + sepal_width + petal_length + petal_width ~ species', data=df)
result = manova.mv_test()
print(result)

                   Multivariate linear model
                                                                
----------------------------------------------------------------
       Intercept         Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0170 4.0000 144.0000 2086.7720 0.0000
         Pillai's trace  0.9830 4.0000 144.0000 2086.7720 0.0000
 Hotelling-Lawley trace 57.9659 4.0000 144.0000 2086.7720 0.0000
    Roy's greatest root 57.9659 4.0000 144.0000 2086.7720 0.0000
----------------------------------------------------------------
                                                                
----------------------------------------------------------------
        species          Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0234 8.0000 288.0000  199.1453 0.0000
         Pillai's trace  1.1919 8.0000 290.00